version: '3.8'

services:
  web:
    build: .
    ports:
      - "10000:10000"
    environment:
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/vidyavaanitrial
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=vidyavaanitrial

volumes:
  mongodb_data:
